booru/booru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('post/', include('post.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booru/home/urls.py
from django.urls import path, include
from .views import MainView

app_name = 'home'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
]

booru/post/urls.py
from django.urls import path, include
from .views import UploadFileView, PostListView, PostDetailView
app_name = 'post'

# Define your URL patterns
urlpatterns = [
    path('upload/', UploadFileView.as_view(), name='upload_file'),
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
]

booru/post/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    RATING_CHOICES = [
        ('S', 'Safe'),
        ('Q', 'Questionable'),
        ('E', 'Explicit'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    posted_date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=200)
    tags = models.CharField(max_length=2000)
    rating = models.CharField(max_length=1, choices=RATING_CHOICES, default='S')
    score = models.IntegerField(default=0, editable=False)
    source = models.CharField(max_length=255, blank=True, default='')
    file = models.FileField(upload_to="files/")

    def __str__(self):
        return f"Post by {self.user.username} - {self.posted_date}"

booru/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    RATING_CHOICES = [
        ('S', 'Safe'),
        ('Q', 'Questionable'),
        ('E', 'Explicit'),
    ]

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect)
    tags = forms.CharField(max_length=2000)

    class Meta:
        model = Post
        fields = ['title', 'tags', 'rating', 'source', 'file']  # Assuming 'file' is the name of your FileField

booru/post/views.py
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post
from django.core.paginator import Paginator

NUM_POSTS = 12

class UploadFileView(FormView):
    template_name = 'post/upload_file.html'
    form_class = PostForm
    success_url = '/post/'  # Change this to the appropriate URL

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home:main')
            
        form = self.get_form()
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            form = self.get_form()
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


# TODO: Make it so you can use the paginator with tags as well
class PostListView(ListView):
    model = Post
    template_name = 'post/post_list.html'
    context_object_name = 'posts'
    paginate_by = NUM_POSTS

    def get_queryset(self):
        # Ordered object of all posts
        queryset = super().get_queryset().order_by('-posted_date')
        tags_param = self.request.GET.get('tags')
        
        # Returns all images if no search tags or if the user searched using the all tag
        if tags_param and tags_param != 'all':

            return self.filter_posts_by_tags(queryset, tags_param)

        return queryset


    def filter_posts_by_tags(self, queryset, tags_param):
        search_tags = self.parse_tags_param(tags_param)
        filtered_posts = []

        for post in queryset:
            post_tags = set(post.tags.split())
            if self.post_contains_tags(post_tags, search_tags):
                filtered_posts.append(post)

        return filtered_posts

    def parse_tags_param(self, tags_param):
        search_tags = tags_param.split()
        include_tags = set()
        exclude_tags = set()

        for tag in search_tags:
            if tag.startswith('-'):
                exclude_tags.add(tag[1:])
            else:
                include_tags.add(tag)

        return include_tags, exclude_tags

    def post_contains_tags(self, post_tags, search_tags):
        include_tags, exclude_tags = search_tags
        return include_tags.issubset(post_tags) and not any(tag in post_tags for tag in exclude_tags)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        paginator = Paginator(queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'post/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['post'] = post
        return context

booru/post/templates/post/post_detail.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">{{ post.title }}</h1>
                    <p class="card-text">Posted by: {{ post.user.username }}</p>
                    <p class="card-text">Posted date: {{ post.posted_date }}</p>
                    <p class="card-text">Tags: {{ post.tags }}</p>
                    <p class="card-text">Rating: {{ post.get_rating_display }}</p>
                    <p class="card-text">Score: {{ post.score }}</p>
                    {% if post.source %}
                    <p class="card-text">Source: <a href="{{ post.source }}">{{ post.source }}</a></p>
                    {% endif %}
                    {% if post.file %}
                        {% if post.file.url %}
                            {% if post.file.url|lower|slice:'-3:' == 'mp4' %}
                                <div class="video-container">
                                    <video width="100%" height="auto" poster="" controls crossorigin>
                                        <source src="{{ post.file.url }}" type="video/mp4">
                                        Your browser does not support the video tag.
                                    </video>
                                </div>
                            {% else %}
                                <img class="img-fluid" src="{{ post.file.url }}" alt="{{ post.title }}">
                            {% endif %}
                        {% endif %}
                    {% else %}
                        <p>No file attached.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrastyles %}
{{ block.super }}
<style>
    .video-container {
        position: relative;
        width: 100%;
        max-width: 800px; /* Adjust this value as needed */
        margin: 0 auto;
    }
</style>
{% endblock %}

booru/post/templates/post/post_list.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2 class="mt-4 mb-4">Post List</h2>
    <div class="row">
        {% for post in page_obj %}
        <div class="col-md-4 mb-4">
            <div class="card">
                {% if post.file %}
                    {% if post.file.url %}
                        <a href="{% url 'post:post_detail' post.id %}">
                            {% if post.file.url|lower|slice:'-3:' == 'mp4' %}
                                <video width="100%" controls poster="{{ post.file.url }}">
                                    <source src="{{ post.file.url }}" type="video/mp4">
                                    Your browser does not support the video tag.
                                </video>
                            {% else %}
                                <img class="card-img-top" src="{{ post.file.url }}" alt="Image">
                            {% endif %}
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <nav aria-label="Pagination">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1{% if request.GET.tags %}&tags={{ request.GET.tags }}{% endif %}" tabindex="-1">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.tags %}&tags={{ request.GET.tags }}{% endif %}">Previous</a>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            <li class="page-item{% if page_obj.number == num %} active{% endif %}">
                <a class="page-link" href="?page={{ num }}{% if request.GET.tags %}&tags={{ request.GET.tags }}{% endif %}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.tags %}&tags={{ request.GET.tags }}{% endif %}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.tags %}&tags={{ request.GET.tags }}{% endif %}">Last</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

booru/post/templates/post/upload_file.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="text-center mb-4">Upload File</h2>
      <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block mt-3">Upload</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}